# Setup
title: FluentTTS
tagline: Text-dependent Fine-grained Style Control for Multi-style TTS
url: https://kchap0118.github.io/fluenttts/
paginate: 1
baseurl: "http://kchap0118.github.io/fluenttts/"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Changhwan Kim
  url: https://kchap.github.io/fluenttts
  email: fluenttts@gmail.com

# Custom vars
version: 3.0.0
